#!/usr/bin/env python
import sys
import argparse
import whois

parser = argparse.ArgumentParser(description='Whois based domain monitoring tool')
parser.add_argument('--config-file', '-C', type=str, help='file containing list of domains')
parser.add_argument('--domains', '-d', type=str, help='standalone comma sep list of domains to check')
args = parser.parse_args()

if len(sys.argv) == 1:
    parser.print_help(sys.stderr)

if args.config_file and not args.domains:
    domains = []
    for domain in open(args.config_file, 'rt'):
        #print(domain.strip())
        domains.append(domain.strip())

    report = {}

    for domain in domains:
        #print(domain)
        w = whois.whois(domain)
        try:
            expiry_date=w['expiration_date'][0].isoformat().split("T")[0]
            report.update({domain: expiry_date})
        except:
            expiry_date=w['expiration_date'].isoformat().split("T")[0]
            report.update({domain: expiry_date})

    for k, v in report.items():
        print(f"{k} expiry_date: {v}")
elif args.domains and not args.config_file:
    print("todo standalone domains check")
    print(args.domains)
elif args.domains and args.config_file:
    print("cannot use both domains and config_file at the same time!", file=sys.stderr)
